export const CREATE_MOVIE = "CREATE_MOVIE";
export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_MOVIE_OPTIMISTIC = "DELETE_MOVIE_OPTIMISTIC";
