export const CREATE_RATING = "CREATE_RATING";
export const LOAD_RATING_SUCCESS = "LOAD_RATING_SUCCESS";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_RATING_OPTIMISTIC = "DELETE_RATING_OPTIMISTIC";
